version: '3.7'

services:

  futurenorthantsdesignsystem:
    container_name: futurenorthantsdesignsystem
    stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 6006:6006
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev